---
title: "AggregatePairedBurnUnburn"
author: "Anna Talucci"
date: "2024-04-18"
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview
Aggregate paired burned unburned data from raw field measurements.


# Packages

```{r}
library(tidyverse)
library(lubridate)
```


# Data

## Estimated measurements

```{r}
firealt = read_csv("../outputs/dataset/2025-02-04_FireAltEstimatedRawData.csv")
```

```{r}
firealt
```

# View summary variables

```{r}
unique(sort(firealt$paired))
```

```{r}
unique(sort(firealt$fireYr))
```
```{r}
unique(sort(firealt$siteId))
```

```{r}
unique(sort(firealt$resName))
```

# Look at specific data

```{r}
firealt %>% filter(tsf==0)
```

```{r}
firealt %>% filter(paired=="p5")
```

# aggregate burn and unburned pairs with summary stats

```{r}
( pairs = firealt%>% 
  group_by(submitNm, distur, paired, fireYr, year, tsf, tsfClass, permaExtent) %>%
  summarise(
    cntryId = paste(unique(cntryId), collapse = ', '),
    lastNm = paste(unique(lastNm), collapse = ', '),
    #lat = mean(lat),
    #lon = mean(lon),
    biome = paste(unique(biome), collapse = ', '),
    #resName = paste(unique(resName), collapse = ', '), 
    #resBiomeName = paste(unique(resBiomeName), collapse = ', '), 
    #fireId = paste(unique(fireId), collapse = ', '),
    #orgDepth = mean(orgDepth),
    #srfH2O = paste(unique(srfH2O), collapse = ', '),
    #topoPos = paste(unique(topoPos), collapse = ', '),
    slope = mean(slope),
    #vegCvr = paste(unique(vegCvr), collapse = ', '),
    tsf = paste(unique(tsf), collapse = ', '),
    tsfClass = paste(unique(tsfClass), collapse = ', '),
    #estDoy = mean(estDoy),
    estDepth = mean(estDepth),
    n = n() )
)
```

```{r}
pairs %>% 
  dplyr::select(-lastNm) %>% 
  filter_all(any_vars(grepl(',', .)))
```

```{r}
names(pairs)
```

```{r}
( pairs_mean_sd_se = firealt %>% 
  group_by(submitNm, distur, paired, fireYr, year, tsf, tsfClass) %>%
  summarise(n = n(),
            mean = mean(estDepth),
            sd   = sd(estDepth, na.rm=TRUE),
            se   = sd / sqrt(n))
)
```

# Check unique values of aggregated data

```{r}
sort(unique(pairs$paired))
```

```{r}
pairs %>% group_by(paired) %>% summarize(n=n())
```

# Write to csv

```{r}
write_csv(pairs , '../outputs/dataset/2025-02-04_FireALTEstimatedPairsBurnedUnburned.csv')
```


# Site Level

```{r}
( SiteLevel = firealt %>% 
  group_by(submitNm, distur, siteId, fireYr, fireId, year) %>%
  summarise(
    cntryId = paste(unique(cntryId), collapse = ', '),
    lastNm = paste(unique(lastNm), collapse = ', '),
    lat = mean(lat),
    lon = mean(lon),
    biome = paste(unique(biome), collapse = ', '),
    #fireId = paste(unique(fireId), collapse = ', '),
    #paired = paste(unique(paired), collapse = ', '),
    #gtProde = paste(unique(gtProbe), collapse = ', '),
    #hitRock = paste(unique(hitRock), collapse = ', '),
    orgDepth = mean(orgDepth),
    #srfH2O = paste(unique(srfH2O), collapse = ', '),
    #topoPos = paste(unique(topoPos), collapse = ', '),
    #slope = mean(slope),
    #vegCvr = paste(unique(vegCvr), collapse = ', '),
    tsf = paste(unique(tsf), collapse = ', '),
    tsfClass = paste(unique(tsfClass), collapse = ', '),
    estDoy = mean(estDoy),
    estDepth = mean(estDepth),
    n = n()
    
    )
)
```

```{r}
SiteLevel %>% 
  dplyr::select(-lastNm) %>% 
  filter_all(any_vars(grepl(',', .)))
```

```{r}
write.csv(SiteLevel, file = "../outputs/dataset/2025-02-04_FireAltEstimatedSiteLevel.csv", row.names=FALSE)
```