---
title: "Site level aggregate"
author: "Anna Talucci"
date: "2025-01-14"
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview
Aggregate paired burned unburned data


# Packages

```{r}
library(tidyverse)
library(lubridate)
```


# Data

## Estimated measurements
```{r}
firealt = read_csv("../data/dataset/FireALTdataset.csv")
```

```{r}
firealt
```

# Summary information

```{r}
unique(sort(firealt$paired))
```

```{r}
unique(sort(firealt$fireYr))
```
```{r}
unique(sort(firealt$plotId))
```

```{r}
unique(sort(firealt$siteId))
```

```{r}
unique(sort(firealt$resName))
```
```{r}
firealt %>% group_by(siteId, plotId, fireYr, year) %>% summarize(n=n())
```

```{r}
firealt %>% group_by(siteId, fireYr, year) %>% summarize(n=n())
```
388 sites 9,432 plots by year

```{r}
firealt %>% group_by(siteId, fireYr) %>% summarize(n=n())
```

# Look at specific data

```{r}
firealt %>% filter(tsf==0)
```

```{r}
firealt %>% filter(paired=="p5")
```

# aggregate burn and unburned pairs with summary stats

```{r}
firealt
```
```{r}
( sitePlot1 = firealt %>% 
  group_by(submitNm, distur, siteId, plotId, fireYr, year) %>%
  summarise(
    cntryId = paste(unique(cntryId), collapse = ', '),
    lastNm = paste(unique(lastNm), collapse = ', '),
    lat = paste(unique(lat), collapse = ', '),
    lon = paste(unique(lon), collapse = ', '),
    month = paste(unique(month), collapse = ', '),
    day = paste(unique(day), collapse = ', '),
    biome = paste(unique(biome), collapse = ', '),
    fireId = paste(unique(fireId), collapse = ', '),
    paired = paste(unique(paired), collapse = ', '),
    gtProde = paste(unique(gtProbe), collapse = ', '),
    hitRock = paste(unique(hitRock), collapse = ', '),
    orgDepth = mean(orgDepth),
    srfH2O = paste(unique(srfH2O), collapse = ', '),
    topoPos = paste(unique(topoPos), collapse = ', '),
    slope = mean(slope),
    vegCvr = paste(unique(vegCvr), collapse = ', '),
    msrDoy = paste(unique(msrDoy), collapse = ', '),
    msrType = paste(unique(msrType), collapse = ', '),
    msrDepth = mean(msrDepth),
    estDoy = paste(unique(msrType), collapse = ', '),
    estDepth = mean(estDepth),
    n = n(),
    tsf = paste(unique(tsf), collapse = ', '),
    tsfClass = paste(unique(tsfClass), collapse = ', '),
    resBiome = paste(unique(resBiome), collapse = ', '),
    resName = paste(unique(resName), collapse = ', '),
    permaExtent = paste(unique(permaExtent), collapse = ', ')
    )
)
```
```{r}
sitePlot1 %>% 
  dplyr::select(-lastNm) %>% 
  filter_all(any_vars(grepl(',', .)))
```

```{r}
( sitePlot2 = firealt %>% 
  group_by(submitNm, distur, siteId, plotId, fireYr, year, month, day) %>%
  summarise(
    cntryId = paste(unique(cntryId), collapse = ', '),
    lastNm = paste(unique(lastNm), collapse = ', '),
    lat = paste(unique(lat), collapse = ', '),
    lon = paste(unique(lon), collapse = ', '),
    #month = paste(unique(month), collapse = ', '),
    #day = paste(unique(day), collapse = ', '),
    biome = paste(unique(biome), collapse = ', '),
    fireId = paste(unique(fireId), collapse = ', '),
    paired = paste(unique(paired), collapse = ', '),
    gtProde = paste(unique(gtProbe), collapse = ', '),
    hitRock = paste(unique(hitRock), collapse = ', '),
    orgDepth = mean(orgDepth),
    srfH2O = paste(unique(srfH2O), collapse = ', '),
    topoPos = paste(unique(topoPos), collapse = ', '),
    slope = mean(slope),
    vegCvr = paste(unique(vegCvr), collapse = ', '),
    msrDoy = paste(unique(msrDoy), collapse = ', '),
    msrType = paste(unique(msrType), collapse = ', '),
    msrDepth = mean(msrDepth),
    estDoy = paste(unique(msrType), collapse = ', '),
    estDepth = mean(estDepth),
    n = n(),
    tsf = paste(unique(tsf), collapse = ', '),
    tsfClass = paste(unique(tsfClass), collapse = ', '),
    resBiome = paste(unique(resBiome), collapse = ', '),
    resName = paste(unique(resName), collapse = ', '),
    permaExtent = paste(unique(permaExtent), collapse = ', ')
    )
)
```

```{r}
sitePlot2 %>% 
  dplyr::select(-lastNm) %>% 
  filter_all(any_vars(grepl(',', .)))
```

```{r}
( sitePlot3 = firealt %>% 
  group_by(submitNm, distur, siteId, plotId, fireYr, year, month, day, lat, lon) %>%
  summarise(
    cntryId = paste(unique(cntryId), collapse = ', '),
    lastNm = paste(unique(lastNm), collapse = ', '),
    #lat = paste(unique(lat), collapse = ', '),
    #lon = paste(unique(lon), collapse = ', '),
    #month = paste(unique(month), collapse = ', '),
    #day = paste(unique(day), collapse = ', '),
    biome = paste(unique(biome), collapse = ', '),
    fireId = paste(unique(fireId), collapse = ', '),
    paired = paste(unique(paired), collapse = ', '),
    gtProde = paste(unique(gtProbe), collapse = ', '),
    hitRock = paste(unique(hitRock), collapse = ', '),
    orgDepth = mean(orgDepth),
    srfH2O = paste(unique(srfH2O), collapse = ', '),
    topoPos = paste(unique(topoPos), collapse = ', '),
    slope = mean(slope),
    vegCvr = paste(unique(vegCvr), collapse = ', '),
    msrDoy = paste(unique(msrDoy), collapse = ', '),
    msrType = paste(unique(msrType), collapse = ', '),
    msrDepth = mean(msrDepth),
    estDoy = paste(unique(estDoy), collapse = ', '),
    estDepth = mean(estDepth),
    n = n(),
    tsf = paste(unique(tsf), collapse = ', '),
    tsfClass = paste(unique(tsfClass), collapse = ', '),
    resBiome = paste(unique(resBiome), collapse = ', '),
    resName = paste(unique(resName), collapse = ', '),
    permaExtent = paste(unique(permaExtent), collapse = ', ')
    )
)
```

```{r}
sitePlot3 %>% 
  dplyr::select(-lastNm) %>% 
  filter_all(any_vars(grepl(',', .)))
```

```{r}
( PlotLevel4 = firealt %>% 
  group_by(submitNm, distur, siteId, plotId, fireYr, year) %>%
  summarise(
    cntryId = paste(unique(cntryId), collapse = ', '),
    lastNm = paste(unique(lastNm), collapse = ', '),
    lat = mean(lat),
    lon = mean(lon),
    biome = paste(unique(biome), collapse = ', '),
    fireId = paste(unique(fireId), collapse = ', '),
    paired = paste(unique(paired), collapse = ', '),
    gtProde = paste(unique(gtProbe), collapse = ', '),
    hitRock = paste(unique(hitRock), collapse = ', '),
    orgDepth = mean(orgDepth),
    srfH2O = paste(unique(srfH2O), collapse = ', '),
    topoPos = paste(unique(topoPos), collapse = ', '),
    slope = mean(slope),
    vegCvr = paste(unique(vegCvr), collapse = ', '),
    estDoy = paste(unique(estDoy), collapse = ', '),
    estDepth = mean(estDepth),
    n = n(),
    tsf = paste(unique(tsf), collapse = ', '),
    tsfClass = paste(unique(tsfClass), collapse = ', '),
    resBiome = paste(unique(resBiome), collapse = ', '),
    resName = paste(unique(resName), collapse = ', '),
    permaExtent = paste(unique(permaExtent), collapse = ', ')
    )
)
```

```{r}
PlotLevel4 %>% 
  dplyr::select(-lastNm) %>% 
  filter_all(any_vars(grepl(',', .)))
```
```{r}
names(PlotLevel4)
```
```{r}
firealt %>% filter(submitNm=="Olefeldt") %>% filter(distur=="unburned") %>% filter(siteId == "camsell_unburn") %>% filter(plotId=="1-1")
```


```{r}
firealt %>% 
  group_by(resBiome, resName, submitNm, distur, permaExtent, siteId, plotId,  fireYr, fireId, tsf, tsfClass) %>%
  summarise(n = n(),
            mean = mean(estDepth),
            sd   = sd(estDepth, na.rm=TRUE),
            se   = sd / sqrt(n))

```
